site_name: How to learn test automation
theme:
  name: material
  palette:
    primary: teal
  font:
    code: Jetbrains Mono
  features:
    - navigation.tabs
google_analytics:
  - UA-177852015-1
  - auto
markdown_extensions:
  - meta